GO_EASY_ON_ME = 1
SDKVERSION = 9.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = BurstModeiOS9
BurstModeiOS9_FILES = Tweak.xm
BurstModeiOS9_FRAMEWORKS = AudioToolbox UIKit
BurstModeiOS9_LIBRARIES = MobileGestalt substrate
BurstModeiOS9_INSTALL_PATH = /Library/Application Support/BurstMode

include $(THEOS_MAKE_PATH)/library.mk
