GO_EASY_ON_ME = 1
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = BurstModeiOS56
BurstModeiOS56_FILES = Tweak.xm
BurstModeiOS56_FRAMEWORKS = AudioToolbox UIKit
BurstModeiOS56_INSTALL_PATH = /Library/Application Support/BurstMode
BurstModeiOS56_LIBRARIES = substrate

include $(THEOS_MAKE_PATH)/library.mk
