GO_EASY_ON_ME = 1
SDKVERSION = 10.2

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = BurstModeiOS10
BurstModeiOS10_FILES = Tweak.xm
BurstModeiOS10_FRAMEWORKS = AudioToolbox UIKit
BurstModeiOS10_LIBRARIES = MobileGestalt substrate
BurstModeiOS10_INSTALL_PATH = /Library/Application Support/BurstMode

include $(THEOS_MAKE_PATH)/library.mk
