GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = BurstModeiOS8
BurstModeiOS8_FILES = Tweak.xm
BurstModeiOS8_FRAMEWORKS = AudioToolbox UIKit
BurstModeiOS8_LIBRARIES = MobileGestalt substrate
BurstModeiOS8_INSTALL_PATH = /Library/Application Support/BurstMode

include $(THEOS_MAKE_PATH)/library.mk
